title: 'WEB ATELIER (UDIT) – Web Foundations'
description: 'Canonical lessons, methodology, and templates for ATELIER UDIT.'
url: 'https://ruvebal.github.io'
baseurl: '/web-atelier-udit'
repository: 'ruvebal/web-atelier-udit'
source: docs
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 parse_block_html: true
 parse_span_html: true
 show_warnings: false
 auto_ids: true
 auto_id_stripping: true

 # Proper British curly quotes
 smart_quotes: [lsquo, rsquo, ldquo, rdquo]

 # Prefer real Unicode characters for punctuation & symbols
 entity_output: as_char

 # Typographic goodies
 typographic_symbols:
  hellip: '…'
  ndash: '–'
  mdash: '—'
  laquo: '«'
  raquo: '»'

 # Footnotes (beautiful endnotes section)
 footnote_nr: 1
 footnote_backlink: '↩'
 footnote_backlink_inline: true
 footnote_backlink_class: 'footnote-back'
 footnote_prefix: ''

 # IDs and ToC
 toc_levels: 2..4

 # Math if needed (remove if not)
 # math_engine: katex
 # math_engine_opts:
 #  output: html
theme: null

highlighter: rouge

permalink: /:categories/:path/

# Process any file with front matter, including nested lessons in es/ and en/
include:
 - lessons
 - assets
 - _data
 - _plugins

# Exclude CI and dev artifacts
exclude:
 - node_modules
 - vendor
 - Gemfile
 - Gemfile.lock
 - package.json
 - package-lock.json
 - scripts
 - .github

# Plugins available on GitHub Pages via 'github-pages' gem
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
 lessons:
  output: true
  permalink: /lessons/:lang/:slug/
 bibliography:
  output: true
  permalink: /bibliography/:lang/
 methodology:
  output: true
  permalink: /methodology/:lang/
 references:
  output: true
  permalink: /references/:lang/
defaults:
 - scope: { path: '_lessons', type: 'lessons' }
   values:
    layout: lesson
 - scope: { path: '_bibliography', type: 'bibliography' }
   values:
    layout: bibliography
 - scope: { path: '_methodology', type: 'methodology' }
   values:
    layout: methodology
 - scope:
    path: 'lessons/es'
   values:
    lang: 'es'
    layout: 'lesson'
 - scope:
    path: 'lessons/en'
   values:
    lang: 'en'
    layout: 'lesson'
