name: Link Check

on:
 pull_request:
 push:
  branches: [main]

jobs:
 lychee:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Set up Ruby
     uses: ruby/setup-ruby@v1
     with:
      ruby-version: '3.2'

   - uses: actions/setup-node@v4
     with:
      node-version: '20'

   - uses: pnpm/action-setup@v4
     with:
      version: 9

   - name: Install Node.js dependencies
     working-directory: web-foundations
     run: pnpm install --frozen-lockfile

   - name: Install Jekyll dependencies
     working-directory: web-foundations
     run: |
      bundle install --path vendor/bundle

   - name: Build site (Jekyll)
     working-directory: web-foundations
     run: |
      npm run build

   - name: Link check (lychee)
     id: lychee
     uses: lycheeverse/lychee-action@v1
     with:
      args: >-
       --verbose
       --no-progress
       --accept 200,429
       --config .lychee.toml
       web-foundations/_site
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   - name: Fail on broken links
     if: ${{ steps.lychee.outputs.exit_code != 0 }}
     run: exit 1
